triggers:
  - event_type: meya.front.event.agent.assign
    bot: bot.status

steps:
  - if: >-
      (@
        flow.event.data.payload.target.data.email == vault.front.bot_teammate_email
      )
    then:
      jump: complete
    else: next
  - user_load: (@ flow.event.data.user_id )
  - status: Conversation assigned to (@ flow.result.name )
  - end

  - (complete)
  - if: (@ vault.front.mode == "ticketing" )
    then:
      flow: flow.front.ticketing.complete
      async: true
      bot: bot.default
    else:
      flow: flow.front.tracking.complete
      async: true
      bot: bot.default
