triggers:
  - event_type: meya.front.event.tag.add

steps:
  - value: (@ flow.event.data.payload.name )
    case:
      HIGH PRIORITY:
        jump: high_priority
    default: end

  - (high_priority)
  - status: Your issue is being handled with high priority
