triggers:
  - keyword: escalate_ticket

steps:
  - ask: What is your name?
  - user_set: name
  - ask: What is your email address?
  - user_set: email
  - ask: Leave a message and we'll get back to you shortly by email
  - flow_set: message

