triggers:
  - keyword: ticketing_create

steps:
  - say: One moment while I find someone to help...

  - type: meya.util.text.component.random_hex
  - flow_set: thread_ref
  - type: meya.front.component.conversation.create
    subject: (@ flow.subject )
    thread_ref: (@ flow.thread_ref )
    attachments_url: [] # TODO Remove
    text: x # TODO Remove
    integration: integration.front
