triggers:
  - keyword: ticketing_create

steps:
  - say: One moment while I find someone to help...

  - type: meya.front.component.conversation.update
    integration: integration.front
    assignee_email:
  - type: meya.front.component.conversation.create
    subject: (@ flow.subject )
    attachments_url: []
    text: TODO
    integration: integration.front
