triggers:
  - catchall

steps:
  - if: >-
      (@
        flow.get("event")
        and flow.event.data.integration_id == "integration.front"
      )
    then: next
    else:
      jump: human
  - flow: flow.nlu.inbound
    transfer: true
    data:
      result: (@ flow.result )

  - (human)
  - say: Sorry, I don't understand. Would you like to talk to customer support?
    quick_replies:
      - text: Yes
        action:
          flow: flow.front.human
          transfer: true
      - text: No thanks
        action:
          flow: flow.restart
          transfer: true
