triggers:
  - catchall

steps:
  - if: (@ flow.get("event") and flow.event.data.integration_id == "integration.front"
      )
    then:
      flow: flow.nlu.inbound
      transfer: true
      data:
        result: (@ flow.result )
    else: next

  - say: Sorry, I don't understand. Would you like to leave a message?
    quick_replies:
      - text: Yes, I want to leave a message
        action:
          flow: flow.front.human
          transfer: true
      - text: No thanks
        action:
          flow: flow.restart
          transfer: true
