triggers:
  - keyword: shipping

steps:
  - if: (@ flow.get("dialogflow_response") )
    then: next
    else:
      jump: full_list
  - flow_set:
      country: (@ flow.dialogflow_response.queryResult.parameters.get("geo-country"))
  - if: (@ flow.country|length > 0 )
    then: next
    else:
      jump: full_list
  - say: Yes 🎉 we ship to (@ flow.country ) for an additional $99.99
  - delay: 1
  - say: Note that this includes all taxes and duties.
    quick_replies:
      - text: Got it
        action:
          flow: flow.start
          transfer: true
  - flow: flow.restart
    transfer: true
  - end

  - (full_list)
  - say: We ship to US and Canada
    quick_replies:
      - text: Got it
        action:
          flow: flow.start
          transfer: true
  - flow: flow.restart
    transfer: true
