triggers:
  - type: page_open
    when: (@ not thread.open_page )
  - keyword: start

steps:
  - thread_set:
      open_page: true
  - say: Hey, welcome! What can I help you with?
    quick_replies:
      - text: General questions
        action:
          flow: flow.faq.general
      - text: Product questions
        action:
          flow: flow.faq.product
      - text: Orders & order status
        action:
          flow: flow.faq.orders
      - text: Shipping & delivery
        action:
          flow: flow.nlu.shipping
      - text: Returns
        action:
          flow: flow.faq.returns
      - text: Talk to support
        action:
          flow: flow.front.human
