triggers:
  - type: page_open
    when: (@ not thread.open_page )
  - keyword: start

steps:
  - thread_set:
      open_page: true
  - flow: flow.front.contact.create_or_update
  - say: Hi, (@ user.name )! Welcome to Loyalty Rewards Help.
  - flow: flow.restart
    data:
      text: What can I do for you today?
