triggers:
  - agent_command: ^/call_back$

steps:
  # Publish as the agent
  - flow_set:
      event_user_id: (@ flow.event.data.user_id )

  - ask_form: Can I have your phone number so I can call you back in a few minutes?
    icon: (@ config.icon.phone )
    label: Phone
