triggers:
  - regex: escalate

steps:
  - if: (@ user.name )
    then:
      jump: escalate
    else: next
  - ask: What's your name?
  - user_set: name
  - say: Nice to meet, you (@ user.name )! 👋

  - (escalate)
  # We can route to different flows depending on whether we're in tracking mode or ticketing mode. In this case,
  # if we're in tracking mode, we'll assign the conversation to an agent. If we're in ticketing mode, we'll just
  # create the conversation.
  - if: (@ vault.front.mode == "ticketing" )
    then:
      flow: flow.front.ticketing.create
      transfer: true
    else: next

  - flow: flow.front.teams.shift.team_shift
  - if: (@ flow.support_available )
    then: next
    else:
      jump: support_offline

  - note: This note appears before agent escalation

  - say: One moment while I find someone to help...
  - type: meya.front.component.conversation.update
    integration: integration.front
    assignee_email: (@ vault.front.agent_email )

  - note: This note appears after agent escalation
  - end

  - (support_offline)
  - say: None of our agents are available at the moment. Please try again later.
