triggers:
  - keyword: human

steps:
  - thread_set:
      mode: prechat

  - flow: flow.front.contact.create_or_update

  - ask: What type of question do you have?
    quick_replies:
      - Points
      - Rewards
      - Shipping
      - Other
  - note: Question type (@ flow.result )

  - if: (@ flow.result == "Points" )
    then:
      flow: flow.front.points_question
    else:
      ask: What is your question?

  - flow: flow.front.teammates.check_available

  - if: (@ vault.front.mode == "ticketing" )
    then:
      flow: flow.front.ticketing.escalate
      data:
        subject: (@ flow.result )
      transfer: true
    else:
      flow: flow.front.tracking.escalate
      data:
        subject: (@ flow.result )
      transfer: true
