triggers:
  - keyword: human

steps:
  - flow: flow.front.contact.create

  - say: What type of question do you have?
  - select: Question type
    options:
      - Points
      - Rewards
      - Shipping
      - Other
  - note: Question type (@ flow.result )

  - ask: What is your question?

  - if: (@ vault.front.mode == "ticketing" )
    then:
      flow: flow.front.ticketing.escalate
      data:
        subject: (@ flow.result )
      transfer: true
    else:
      flow: flow.front.tracking.escalate
      data:
        subject: (@ flow.result )
      transfer: true
