triggers:
  - keyword: front_get_teammate_shift

steps:
  # Retrieve the support team's shift schedule from Front so we can determine if anyone is available.
  - type: meya.front.component.teams.shifts.list
    team_id: (@ vault.front.team_id )
    integration: integration.front

  # Parse the shift data returned by Front.
  - type: component.front.parse_shift_times
    shifts: (@ flow.result._results )
  - end:
      support_available: (@ flow.result )
