triggers:
  - expect: dialogflow
    integration: integration.google.dialogflow

steps:
  - match:
      ^smalltalk\.:
        flow: flow.nlu.smalltalk
        data: (@ flow )
        transfer: true
      ^shipping$:
        flow: flow.shipping
        data: (@ flow )
        transfer: true
    default:
      flow: flow.catchall
      transfer: true
