triggers:
  - keyword: front_create_contact

steps:
  - if: (@ user.name )
    then:
      jump: create
    else: next
  - ask: Name?
  - user_set: name

  - (create)
  # Look up the custom user ID that was passed in to the Orb's connectionOptions. It can be used as a custom
  # Front contact ID.
  - type: meya.user.component.try_reverse_lookup
    integration: integration.orb
  - flow_set: handle

  # Check if the user already exists in Front.
  - type: meya.front.component.contact.get
    handle: (@ flow.handle )
    integration: integration.front
  - if: (@ flow.result )
    then: end
    else: next

  # Create the contact.
  - type: meya.front.component.contact.create
    name: (@ user.name )
    is_spammer: false
    handle: (@ flow.handle ) # A handle is a custom ID that can be used to access the Front contact later.
    link: false # Link the Front contact to the Meya user.
    integration: integration.front
