triggers:
  - keyword: create_contact

steps:
  - type: meya.user.component.try_reverse_lookup
    integration: integration.orb
  - if: (@ flow.result )
    then: end
    else: next

  - type: meya.front.component.contact.create_or_update
    integration: integration.front
    name: (@ user.name )
    handle: app/(@ flow.result )
