triggers:
  - keyword: create_contact

steps:
  - type: meya.user.component.try_reverse_lookup
    integration: integration.front
  - if: (@ flow.result )
    then: end
    else: next

  - type: meya.front.component.contact.create
    integration: integration.front
    name: (@ user.name )
